# run docker-compose -f stack.yml up [postgres | mongo]
version: '3.1'

services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  adminer:
#    image: adminer:4-standalone
#    restart: always
#    ports:
#      - 8080:8080


  mongo:
    image: mongo:4.2.7-bionic
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
#    command: --serviceExecutor adaptive --wiredTigerCacheSizeGB 1.5

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

volumes:
  postgres-data:
  mongo-data:

